const lang = {
    en: {
        tagline1:'Download Youtube',
        tagline2:'Thumbnails in Snap',
        searchPlaceHolder : 'Enter Youtube link',
        searchBtn: 'Search',
        getThumbNailBtn: 'Get thumbnail',
        multiRes:'Multiple resolution available',
        freeDownloads:'Free Download',
        MultipleRes: 'Multiple Resolution',
        UnlinmitedDownloads: 'Unlinmited Downloads',
        howItWorks:'How it works?',
        copyYoutubeLink:'Copy YouTube link',
        copyYoutubeLinkDesc:'Select the desired video and copy the link on YouTube',
        generateThumbnail:'Generate thumbnail',
        generateThumbnailDesc:'Use I Youtube Thumbnail Downloader to effortlessly generate thumbnail',
        downloadThumbnail:'Download thumbnail',
        downloadThumbnailDesc:'Select your preferred resolution and download the thumbnail',
        faqs:'Frequently asked questions',
        question1:'How should I download youtube thumbnail?',
        question2:'How should I download youtube thumbnail?',
        question3:'How should I download youtube thumbnail?',
        question4:'How should I download youtube thumbnail?',
        question5:'How should I download youtube thumbnail?',
        question6:'How should I download youtube thumbnail?',
        question7:'How should I download youtube thumbnail?',
        question8:'How should I download youtube thumbnail?',
        question9:'How should I download youtube thumbnail?',
        question10:'How should I download youtube thumbnail?',
        question11:'How should I download youtube thumbnail?',
        question1Con:'',
        question2Con:'',
        question3Con:'',
        question4Con:'',
        question5Con:'',
        question6Con:'',
        question7Con:'',
        question8Con:'',
        question9Con:'',
        question10Con:'',
        question11Con:'',
        websitename:'iyoutubethumnail',
        webSiteEmail:'iyoutubethumbnail.com',
        rights:'All rights reserved © 2024 iyoutubethumnail',
        termAndCon:'TERMS AND CONDITIONS',
        privacy:'PRIVACY POLICY',
        highQuality:'High Resolution Quality (480 x 360)',
        mediumQuality:'Medium Resolution Quality (480 x 360)',
        standardQuality:'Standard Resolution Quality (480 x 360)',
        maxQuality:'Maximum Resolution Quality (480 x 360)',
        downloadImage:'Download Image',
        wasThisHelpFull:'Was this helpful',
        supportUs:'Help us grow by sharing the link with your friends',
        copyLink:'Copy Link'
    },
    span: {
        tagline1:'Descargar Youtube',
        tagline2:'Miniaturas en Snap',
        searchPlaceHolder : 'Ingrese al enlace de Youtube',
        searchBtn: 'Buscar',
        getThumbNailBtn: 'Obtener miniatura',
        multiRes:'Resolución múltiple disponible',
        freeDownloads:'Descarga gratis',
        MultipleRes: 'Resolución múltiple',
        UnlinmitedDownloads: 'Descargas ilimitadas',
        howItWorks:'Cómo funciona?',
        copyYoutubeLink:'Copiar enlace de YouTube',
        copyYoutubeLinkDesc:'Seleccione el vídeo deseado y copie el enlace en YouTube.',
        generateThumbnail:'Generar miniatura',
        generateThumbnailDesc:'I Descargador de miniaturas de Youtube',
        downloadThumbnail:'Descargar miniatura',
        downloadThumbnailDesc:'Seleccione su resolución preferida y descargue la miniatura',
        faqs:'Preguntas frecuentes',
        question1:'¿Cómo debo descargar la miniatura de YouTube?',
        question2:'¿Cómo debo descargar la miniatura de YouTube?',
        question3:'¿Cómo debo descargar la miniatura de YouTube?',
        question4:'¿Cómo debo descargar la miniatura de YouTube?',
        question5:'¿Cómo debo descargar la miniatura de YouTube?',
        question6:'¿Cómo debo descargar la miniatura de YouTube?',
        question7:'¿Cómo debo descargar la miniatura de YouTube?',
        question8:'¿Cómo debo descargar la miniatura de YouTube?',
        question9:'¿Cómo debo descargar la miniatura de YouTube?',
        question10:'¿Cómo debo descargar la miniatura de YouTube?',
        question11:'¿Cómo debo descargar la miniatura de YouTube?',
        question1Con:'',
        question2Con:'',
        question3Con:'',
        question4Con:'',
        question5Con:'',
        question6Con:'',
        question7Con:'',
        question8Con:'',
        question9Con:'',
        question10Con:'',
        question11Con:'',
        websitename:'iyoutubethumnail',
        webSiteEmail:'iyoutubethumbnail.com',
        rights:'Todos los derechos reservados © 2024 iyoutubethumnail',
        termAndCon:'TÉRMINOS Y CONDICIONES',
        privacy:'POLÍTICA DE PRIVACIDAD',
        highQuality:'Calidad de alta resolución (480 x 360)',
        mediumQuality:'Calidad de resolución media (320 x 180)',
        standardQuality:'Calidad de resolución estándar (640 x 480)',
        maxQuality:'Calidad de resolución máxima (1280 x 720)',
        downloadImage:'Descargar imagen', 
        wasThisHelpFull:'¿Fue esto útil?',
        supportUs:'Ayúdanos a crecer compartiendo el enlace con tus amigos.',
        copyLink:'Copiar link'
    },
    hi: {
        tagline1: 'तेजी से यूट्यूब ',
        tagline2:'थंबनेल डाउनलोड करें',
        searchPlaceHolder : 'यूट्यूब लिंक दर्ज करें',
        searchBtn: 'खोज',
        getThumbNailBtn: 'थंबनेल प्राप्त करें',
        multiRes:'एकाधिक रिज़ॉल्यूशन उपलब्ध है',
        freeDownloads:'मुफ्त डाउनलोड',
        MultipleRes: 'एकाधिक संकल्प',
        UnlinmitedDownloads: 'असीमित डाउनलोड',
        howItWorks:'यह काम किस प्रकार करता है?',
        copyYoutubeLink:'यूट्यूब लिंक कॉपी करें',
        copyYoutubeLinkDesc:'वांछित वीडियो का चयन करें और यूट्यूब पर लिंक को कॉपी करें',
        generateThumbnail:'थंबनेल जनरेट करें',
        generateThumbnailDesc:'आसानी से थंबनेल जेनरेट करने के लिए यूट्यूब थंबनेल डाउनलोडर का उपयोग करें',
        downloadThumbnail:'थंबनेल डाउनलोड करें',
        downloadThumbnailDesc:'अपना पसंदीदा रिज़ॉल्यूशन चुनें और थंबनेल डाउनलोड करें',
        faqs:'अक्सर पूछे जाने वाले प्रश्नों',
        question1:'¿Cómo debo descargar la miniatura de YouTube?',
        question2:'¿Cómo debo descargar la miniatura de YouTube?',
        question3:'¿Cómo debo descargar la miniatura de YouTube?',
        question4:'¿Cómo debo descargar la miniatura de YouTube?',
        question5:'¿Cómo debo descargar la miniatura de YouTube?',
        question6:'¿Cómo debo descargar la miniatura de YouTube?',
        question7:'¿Cómo debo descargar la miniatura de YouTube?',
        question8:'¿Cómo debo descargar la miniatura de YouTube?',
        question9:'¿Cómo debo descargar la miniatura de YouTube?',
        question10:'¿Cómo debo descargar la miniatura de YouTube?',
        question11:'¿Cómo debo descargar la miniatura de YouTube?',
        question1Con:'',
        question2Con:'',
        question3Con:'',
        question4Con:'',
        question5Con:'',
        question6Con:'',
        question7Con:'',
        question8Con:'',
        question9Con:'',
        question10Con:'',
        question11Con:'',
        websitename:'iyoutubethumnail',
        webSiteEmail:'iyoutubethumbnail.com',
        rights:'सर्वाधिकार सुरक्षित © 2024 iyoutubethumnail',
        termAndCon:'नियम और शर्तें',
        privacy:'गोपनीयता नीति',
        highQuality:'उच्च रिज़ॉल्यूशन गुणवत्ता (480px x 360 px)',
        mediumQuality:'मध्यम रिज़ॉल्यूशन गुणवत्ता (320px x 180px)',
        standardQuality:'मानक रिज़ॉल्यूशन गुणवत्ता (640px x 480px)',
        maxQuality:'अधिकतम रिज़ॉल्यूशन गुणवत्ता (1280px x 720px)',
        downloadImage:'छवि डाउनलोड करें',
        wasThisHelpFull:'क्या ये सहायक था',
        supportUs:'अपने दोस्तों के साथ लिंक साझा करके हमें आगे बढ़ने में मदद करें',
        copyLink:'लिंक की प्रतिलिपि करें'
    },
    ger: {
        tagline1:'Laden Sie YouTube herunter',
        tagline2:'Miniaturansichten in Snap',
        searchPlaceHolder : 'Bitte gib den YouTube-Link ein.',
        searchBtn: 'Suche',
        getThumbNailBtn: 'Bild erhalten',
        multiRes:'Mehrere Auflösungen verfügbar',
        freeDownloads:'Kostenloser Download',
        MultipleRes: 'Mehrere Auflösungen',
        UnlinmitedDownloads: 'Unbegrenzte Downloads',
        howItWorks:'Wie funktioniert es?',
        copyYoutubeLink:'Kopiere den YouTube-Link',
        copyYoutubeLinkDesc:'Wähle das gewünschte Video aus und kopiere den Link auf YouTube.',
        generateThumbnail:'Erzeuge ein Vorschaubild',
        generateThumbnailDesc:'Nutze iYouTubeThumbnail Downloader, um mühelos Vorschaubilder zu generieren.',
        downloadThumbnail:'Vorschaubild herunterladen',
        downloadThumbnailDesc:'Wähle deine bevorzugte Auflösung und lade das Vorschaubild herunter.',
        faqs:'Häufig gestellte Fragen',
        question1:'¿Cómo debo descargar la miniatura de YouTube?',
        question1Con:'',
        question2Con:'',
        question3Con:'',
        question2:'¿Cómo debo descargar la miniatura de YouTube?',
        question3:'¿Cómo debo descargar la miniatura de YouTube?',
        question4:'How should I download youtube thumbnail?',
        question5:'How should I download youtube thumbnail?',
        question6:'How should I download youtube thumbnail?',
        question7:'How should I download youtube thumbnail?',
        question8:'How should I download youtube thumbnail?',
        question9:'How should I download youtube thumbnail?',
        question10:'How should I download youtube thumbnail?',
        question11:'How should I download youtube thumbnail?',
        question1Con:'',
        question2Con:'',
        question3Con:'',
        question4Con:'',
        question5Con:'',
        question6Con:'',
        question7Con:'',
        question8Con:'',
        question9Con:'',
        question10Con:'',
        question11Con:'',
        websitename:'iyoutubethumnail',
        webSiteEmail:'iyoutubethumbnail.com',
        rights:'All rights reserved © 2024 iYouTubeThumbnail',
        termAndCon:'TERMS AND CONDITIONS',
        privacy:'PRIVACY POLICY',
        highQuality:'Hohe Auflösungsqualität (480 x 360)',
        mediumQuality:'Mittlere Auflösungsqualität (480 x 360)',
        standardQuality:'Standard-Auflösungsqualität (480 x 360)',
        maxQuality:'Maximale Auflösungsqualität (480 x 360)',
        downloadImage:'Bild herunterladen',
        wasThisHelpFull:'War das hilfreich?',
        supportUs:'Helfen Sie uns zu wachsen, indem Sie den Link mit Ihren Freunden teilen',
        copyLink:'Link kopieren'
    }
}

export default lang